<a href="https://colab.research.google.com/github/silvia-jesus/CAR_Labrea/blob/main/CAR_RL_Labrea_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **CAR_RL_Labrea_01.ipynb**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import os

if not os.path.exists('/content/drive/MyDrive/CAR_RL_Labrea/OUTPUT'):
  os.makedirs('/content/drive/MyDrive/CAR_RL_Labrea/OUTPUT')

from pathlib import Path
Path('./').mkdir(parents=True, exist_ok=True)

In [ ]:
import time

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
!pip install geopandas
import geopandas as gpd

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 14.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.7/7.7 MB 70.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.1/16.1 MB 61.7 MB/s eta 0:00:00


In [ ]:
!sudo apt install libspatialindex-dev
!pip install rtree
!pip install pygeos

import rtree
import pygeos
gpd.options.use_pygeos = True
USE_PYGEOS=1

Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libspatialindex-c6 libspatialindex6
The following NEW packages will be installed:
  libspatialindex-c6 libspatialindex-dev libspatialindex6
0 upgraded, 3 newly installed, 0 to remove and 23 not upgraded.
Need to get 340 kB of archives.
After this operation, 1,538 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu focal/universe amd64 libspatialindex6 amd64 1.9.3-1build1 [266 kB]
Get:2 http://archive.ubuntu.com/ubuntu focal/universe amd64 libspatialindex-c6 amd64 1.9.3-1build1 [58.3 kB]
Get:3 http://archive.ubuntu.com/ubuntu focal/universe amd64 libspatialindex-dev amd64 1.9.3-1build1 [16.0 kB]
Fetched 340 kB in 1s (448 kB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dia

/usr/local/lib/python3.9/dist-packages/geopandas/_compat.py:123: UserWarning: The Shapely GEOS version (3.11.1-CAPI-1.17.1) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py:3249: UserWarning: Shapely 2.0 is installed, but because PyGEOS is also installed, GeoPandas will still use PyGEOS by default for now. To force to use and test Shapely 2.0, you have to set the environment variable USE_PYGEOS=0. You can do this before starting the Python process, or in your code before importing geopandas:

import os
os.environ['USE_PYGEOS'] = '0'
import geopandas

In a future release, GeoPandas will switch to using Shapely by default. If you are using PyGEOS directly (calling PyGEOS functions on geometries from GeoPandas), this will then stop working and you are encouraged to migrate from PyGEOS to Shapely 2.0 (https://shapely.readthedocs

In [ ]:
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
from mpl_toolkits.axes_grid1.anchored_artists import AnchoredSizeBar #para escala do mapa
import matplotlib.font_manager as fm

In [ ]:
import io
import requests

In [ ]:
albers = '+proj=aea +lat_1=-5 +lat_2=-42 +lat_0=-32 +lon_0=-60 +x_0=0 +y_0=0 +ellps=aust_SA +units=m +no_defs '

**Boletim CAR**  (https://dados.agricultura.gov.br/dataset/cadastro-ambiental-rural)  
**Fonte:**	https://www.car.gov.br/temas/  
**Mantenedor:** DRA - Diretoria de Regularização Ambiental  
**Última Atualização:**	6 de Fevereiro de 2023, 14:51 (UTC-03:00)  
**Criado:**	21 de Outubro de 2021, 16:02 (UTC-03:00)  
**encoding:** utf-8  
**Órgão - Esfera:**	Federal  
**Órgão - Poder:**	Executivo  




ACESSO EM 15/02/2023

In [ ]:
#acesso aos dados no drive
boletim = pd.read_csv('/content/drive/MyDrive/CAR_RL_Labrea/DADOS/imoveis_cadastrados_por_municipio.csv', sep=';')
boletim.head()

uf       municipio  codigo_ibge  numero_de_cadastros  area_cadastrada
0  SP  Vitória Brasil      3556958                  203        4804.3640
1  PI   Avelino Lopes      2201101                 1416       79895.9621
2  MG     Lima Duarte      3138609                 1838       77306.1967
3  SP          Tejupá      3554201                  574       30527.3497
4  BA           Ubatã      2932309                  217        6755.2394

In [ ]:
boletim.dtypes.to_frame()

0
uf                    object
municipio             object
codigo_ibge            int64
numero_de_cadastros    int64
area_cadastrada      float64

In [ ]:
#acesso aos dados via url

# url = 'https://dados.agricultura.gov.br/dataset/58bdc09c-9778-42b9-8fce-7d5c2c4fa211/resource/b89ffa6b-cf9a-4fb6-9f94-c9fcbfc0a6d7/download/imoveis_cadastrados_por_municipio.csv'
# response = requests.get(url)
# content = response.content
# boletim_url = pd.read_csv(url,sep=';')
# boletim_url.head()

**DADOS CAR POR MUNICÍPIO**  
https://www.car.gov.br/publico/imoveis/index

ACESSO EM 14/03/2023

In [ ]:
import glob
import zipfile
import shutil

In [ ]:
if not os.path.exists('/content/drive/MyDrive/CAR_RL_Labrea/OUTPUT/RESERVA_LEGAL/RESERVA_LEGAL_UNZIPPED'):
  os.makedirs('/content/drive/MyDrive/CAR_RL_Labrea/OUTPUT/RESERVA_LEGAL/RESERVA_LEGAL_UNZIPPED')

from pathlib import Path
Path('./').mkdir(parents=True, exist_ok=True)

In [ ]:
if not os.path.exists('/content/drive/MyDrive/CAR_RL_Labrea/OUTPUT/AREA_IMOVEL/AREA_IMOVEL_UNZIPPED'):
  os.makedirs('/content/drive/MyDrive/CAR_RL_Labrea/OUTPUT/AREA_IMOVEL/AREA_IMOVEL_UNZIPPED')

Path('./').mkdir(parents=True, exist_ok=True)

In [ ]:
files_path = '/content/drive/MyDrive/CAR_RL_Labrea/DADOS/CAR/*'
files_list = glob.glob(files_path)

print(len(files_list))
files_list

1


['/content/drive/MyDrive/CAR_RL_Labrea/DADOS/CAR/SHAPE_1302405.zip']

**Organização dos dados de RESERVA LEGAL**

In [ ]:
my_dir = '/content/drive/MyDrive/CAR_RL_Labrea/OUTPUT/RESERVA_LEGAL'

for i in files_list:
  with zipfile.ZipFile(i, mode="r") as archive:
    cod_mun = i.replace('/content/drive/MyDrive/CAR_RL_Labrea/DADOS/CAR/SHAPE_','RL_')
    for member in archive.namelist():
      if member == 'RESERVA_LEGAL.zip':
        source = archive.open(member)
        target = open(os.path.join(my_dir, cod_mun), 'wb')
        with source, target:
          shutil.copyfileobj(source, target)
          print(cod_mun)


RL_1302405.zip


In [ ]:
files_path_RL = '/content/drive/MyDrive/CAR_RL_Labrea/OUTPUT/RESERVA_LEGAL/RL*'
files_list_RL = glob.glob(files_path_RL)

print(len(files_list_RL))
files_list_RL

1


['/content/drive/MyDrive/CAR_RL_Labrea/OUTPUT/RESERVA_LEGAL/RL_1302405.zip']

In [ ]:
for i in files_list_RL:
  unzip = f'{i}!/RESERVA_LEGAL.shp'
  rl = gpd.read_file(unzip)
  rl_reproj = rl.to_crs(albers)
  name = i.replace('/content/drive/MyDrive/CAR_RL_Labrea/OUTPUT/RESERVA_LEGAL/','').replace('.zip','')
  rl_reproj.to_file(f'/content/drive/MyDrive/CAR_RL_Labrea/OUTPUT/RESERVA_LEGAL/RESERVA_LEGAL_UNZIPPED/{name}_102033.shp')
  print(name)

RL_1302405


In [ ]:
if not os.path.exists('/content/drive/MyDrive/CAR_RL_Labrea/OUTPUT/RL_CSV'):
  os.makedirs('/content/drive/MyDrive/CAR_RL_Labrea/OUTPUT/RL_CSV')

Path('./').mkdir(parents=True, exist_ok=True)

In [ ]:
files_list_RL

['/content/drive/MyDrive/CAR_RL_Labrea/OUTPUT/RESERVA_LEGAL/RL_1302405.zip']

In [ ]:
for i in files_list_RL:
  gdf = gpd.read_file(i)
  cdmun = i.replace('/content/drive/MyDrive/CAR_RL_Labrea/OUTPUT/RESERVA_LEGAL/RL_','').replace('.zip','')
  gdf['cd_mun']=cdmun
  gdf.to_csv(f'/content/drive/MyDrive/CAR_RL_Labrea/OUTPUT/RL_CSV/RL_{cdmun}.csv')
  print(cdmun)

1302405


**Organização dos dados da ÁREA DO IMÓVEL**

In [ ]:
my_dir = '/content/drive/MyDrive/CAR_RL_Labrea/OUTPUT/AREA_IMOVEL'

for i in files_list:
  with zipfile.ZipFile(i, mode="r") as archive:
    cod_mun = i.replace('/content/drive/MyDrive/CAR_RL_Labrea/DADOS/CAR/SHAPE_','IM_')
    for member in archive.namelist():
      if member == 'AREA_IMOVEL.zip':
        source = archive.open(member)
        target = open(os.path.join(my_dir, cod_mun), 'wb')
        with source, target:
          shutil.copyfileobj(source, target)
          print(cod_mun)

IM_1302405.zip


In [ ]:
files_path_IM = '/content/drive/MyDrive/CAR_RL_Labrea/OUTPUT/AREA_IMOVEL/IM_*'
files_list_IM = glob.glob(files_path_IM)

print(len(files_list_IM))
files_list_IM

1


['/content/drive/MyDrive/CAR_RL_Labrea/OUTPUT/AREA_IMOVEL/IM_1302405.zip']

In [ ]:
for i in files_list_IM:
  unzip = f'{i}!/AREA_IMOVEL.shp'
  im = gpd.read_file(unzip)
  im_reproj = im.to_crs(albers)
  name = i.replace('/content/drive/MyDrive/CAR_RL_Labrea/OUTPUT/AREA_IMOVEL/','').replace('.zip','')
  im_reproj.to_file(f'/content/drive/MyDrive/CAR_RL_Labrea/OUTPUT/AREA_IMOVEL/AREA_IMOVEL_UNZIPPED/{name}_102033.shp')
  print(name)

IM_1302405


In [ ]:
files_path_IM = '/content/drive/MyDrive/CAR_RL_Labrea/OUTPUT/AREA_IMOVEL/AREA_IMOVEL_UNZIPPED/*shp'
files_list_IM = glob.glob(files_path_IM)

print(len(files_list_IM))
files_list_IM

1


['/content/drive/MyDrive/CAR_RL_Labrea/OUTPUT/AREA_IMOVEL/AREA_IMOVEL_UNZIPPED/IM_1302405_102033.shp']

In [ ]:
if not os.path.exists('/content/drive/MyDrive/CAR_RL_Labrea/OUTPUT/IM_CSV'):
  os.makedirs('/content/drive/MyDrive/CAR_RL_Labrea/OUTPUT/IM_CSV')

from pathlib import Path
Path('./').mkdir(parents=True, exist_ok=True)

In [ ]:
for i in files_list_IM:
  gdf = gpd.read_file(i)
  cdmun = i.replace('/content/drive/MyDrive/CAR_RL_Labrea/OUTPUT/AREA_IMOVEL/AREA_IMOVEL_UNZIPPED/','').replace('_IM_102033.shp','')
  gdf['cd_mun']=cdmun
  gdf.to_csv(f'/content/drive/MyDrive/CAR_RL_Labrea/OUTPUT/IM_CSV/IMOVEL_{cdmun}.csv', encoding = 'latin1')
  print(cdmun)

IM_1302405_102033.shp


**Cobertura da terra (MapBiomas)**  
Coleção 7  
ACESSO EM 11/03/2023

In [ ]:
mb_path = '/content/drive/MyDrive/CAR_RL_Labrea/DADOS/MAPBIOMAS/*tif'
mb_list = glob.glob(mb_path)

mb_list

['/content/drive/MyDrive/CAR_RL_Labrea/DADOS/MAPBIOMAS/mapbiomas-brazil-collection-70-labrea-30km-2020.tif',
 '/content/drive/MyDrive/CAR_RL_Labrea/DADOS/MAPBIOMAS/mapbiomas-brazil-collection-70-labrea-30km-2008.tif',
 '/content/drive/MyDrive/CAR_RL_Labrea/DADOS/MAPBIOMAS/mapbiomas-brazil-collection-70-labrea-30km-2012.tif',
 '/content/drive/MyDrive/CAR_RL_Labrea/DADOS/MAPBIOMAS/mapbiomas-brazil-collection-70-labrea-30km-2016.tif']

In [ ]:
!pip install rasterio
import rasterio as rio
from rasterio.warp import reproject, Resampling, calculate_default_transform


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.1/20.1 MB 58.7 MB/s eta 0:00:00


In [ ]:
if not os.path.exists('/content/drive/MyDrive/CAR_RL_Labrea/OUTPUT/MAPBIOMAS'):
  os.makedirs('/content/drive/MyDrive/CAR_RL_Labrea/OUTPUT/MAPBIOMAS')

Path('./').mkdir(parents=True, exist_ok=True)

In [ ]:
start = time.time()

for i in mb_list:
  with rio.open(i) as src:
    src_transform = src.transform

    dst_transform, width, height = calculate_default_transform(
    src.crs,
    albers,
    src.width,
    src.height,
    *src.bounds
    )

    dst_kwargs = src.meta.copy()
    dst_kwargs.update({
        'crs': albers,
        'transform': dst_transform,
        'width': width,
        'height': height,
        # 'nodata': np.nan
        })


    name = i.replace('/content/drive/MyDrive/CAR_RL_Labrea/DADOS/MAPBIOMAS/mapbiomas-brazil-collection-70-labrea-30km-','').replace('.tif','')
    path = f'/content/drive/MyDrive/CAR_RL_Labrea/OUTPUT/MAPBIOMAS/mapbiomas_{name}_102033.tif'
    with rio.open(path, "w", **dst_kwargs) as dst:
        # iterate through bands

        reproject(
            source=rio.band(src, 1),
            destination=rio.band(dst, 1),
            src_transform=src.transform,
            src_crs=src.crs,
            dst_transform=dst_transform,
            dst_crs=albers,
            resampling=Resampling.nearest,
            )
        print(name)


end= time.time()
duration = end -start

print(f'O processo de reprojeção das imagens durou {duration} segundos.')

2020
2008
2012
2016
O processo de reprojeção das imagens durou 24.58094334602356 segundos.


In [ ]:
mb_path = '/content/drive/MyDrive/CAR_RL_Labrea/OUTPUT/MAPBIOMAS/*102033.tif'
mb_list = glob.glob(mb_path)

mb_list

['/content/drive/MyDrive/CAR_RL_Labrea/OUTPUT/MAPBIOMAS/mapbiomas_2020_102033.tif',
 '/content/drive/MyDrive/CAR_RL_Labrea/OUTPUT/MAPBIOMAS/mapbiomas_2008_102033.tif',
 '/content/drive/MyDrive/CAR_RL_Labrea/OUTPUT/MAPBIOMAS/mapbiomas_2012_102033.tif',
 '/content/drive/MyDrive/CAR_RL_Labrea/OUTPUT/MAPBIOMAS/mapbiomas_2016_102033.tif']

**Recodificação para grandes classes**

In [ ]:
if not os.path.exists('/content/drive/MyDrive/CAR_RL_Labrea/OUTPUT/MAPBIOMAS_RECODE'):
  os.makedirs('/content/drive/MyDrive/CAR_RL_Labrea/OUTPUT/MAPBIOMAS_RECODE')

Path('./').mkdir(parents=True, exist_ok=True)

In [ ]:
values = []

for m in mb_list:
    mb_file = rio.open(m)
    a = mb_file.read(1)
    vals = np.unique (a)
    values.append(vals)
    print (vals)


[ 0  3  4 11 12 15 24 30 33 41]
[ 0  3  4 11 12 15 24 30 33 41]
[ 0  3  4 11 12 15 24 30 33 41]
[ 0  3  4 11 12 15 24 30 33 39 41]


In [ ]:
values = []

for m in mb_list:
    mb_file = rio.open(m)
    a = mb_file.read(1)
    vals = np.unique (a)
    values.append(vals)
    print (vals)

In [ ]:
values_f = [item for sublist in values for item in sublist]
nd = np.unique(values_f)
nd

array([ 0,  3,  4, 11, 12, 15, 24, 30, 33, 39, 41], dtype=uint8)

In [ ]:
for m in mb_list:
    mb_file = rio.open(m)
    a = mb_file.read(1)
    a_meta = mb_file.profile
    a[(a==3)|(a==4)] = 1
    a[(a==11)|(a==12)] = 2
    a[(a==15)|(a==39)|(a==41)] = 3
    a[(a==24)|(a==30)] = 4
    a[(a==33)] = 5
    name = m.replace('/content/drive/MyDrive/CAR_RL_Labrea/OUTPUT/MAPBIOMAS/mapbiomas_','').replace('_102033.tif','')

    with rio.open(f'/content/drive/MyDrive/CAR_RL_Labrea/OUTPUT/MAPBIOMAS_RECODE/{name}_recode.tif', 'w', **a_meta) as dst:
        dst.write(a, 1)
    print (name)


2020
2008
2012
2016
